# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
- group: aws-ecr
- name: patchVersion
  value: $[counter('newonewsPatchVersion', 0)]
- name: tag
  value: '1.0.$(patchVersion)'
- name: awsRegion
  value: 'eu-west-1'
- name: repoName
  value: 'learn/images'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: BuildAndPush
    displayName: Build and Push
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Final Boss/neonews/Dockerfile'
        repository: $(repoName)
        tags: |
          $(tag)
    - script: |
        # Login to ECR
        aws ecr get-login-password --region $(awsRegion) | docker login --username AWS --password-stdin $(AWS_ACCOUNT_ID).dkr.ecr.$(awsRegion).amazonaws.com

        # Tag and Push
        docker tag $(repoName):$(tag) $(AWS_ACCOUNT_ID).dkr.ecr.$(awsRegion).amazonaws.com/$(repoName)/neonews:$(tag)
        docker push $(AWS_ACCOUNT_ID).dkr.ecr.$(awsRegion).amazonaws.com/$(repoName)/neonews:$(tag)
      displayName: 'Push to ECR via AWS CLI'
      env:
        AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
        AWS_ACCOUNT_ID: $(AWS_ACCOUNT_ID)
