trigger: none

variables:
- group: aws-ecr
- name: patchVersion
  value: $[counter('newonewsPatchVersion', 0)]
- name: tag
  value: '1.0.$(patchVersion)'
- name: awsRegion
  value: 'eu-west-1'
- name: repoName
  value: 'neonews'

resources:
- repo: self

stages:
- stage: Test
  displayName: Run Tests
  jobs:
  - job: UnitTests
    displayName: Run Unit Tests
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.12'
        addToPath: true
    - script: |
        python -m pip install --upgrade pip
        pip install -r "$(Build.SourcesDirectory)/Final Boss/neonews/src/requirements.txt"
        pip install pytest flake8
      displayName: 'Install dependencies'
    - script: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      displayName: 'Run Linting (flake8)'
    - script: |
        export PYTHONPATH=$PYTHONPATH:"$(Build.SourcesDirectory)/Final Boss/neonews/src"
        python -m pytest "$(Build.SourcesDirectory)/Final Boss/neonews/tests/test_app.py"
      displayName: 'Run unit tests'
      env:
        NEWSDATA_API_KEY: 'test-key'
        DYNAMODB_TABLE: 'neonews-demo'
        S3_BUCKET_NAME: 'neonews-bucket-demo-123'
        AWS_REGION: 'eu-west-1'
- stage: Build
  dependsOn: Test
  condition: succeeded()
  displayName: Build image
  jobs:
  - job: BuildAndPush
    displayName: Build and Push
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Final Boss/neonews/Dockerfile'
        repository: $(repoName)
        tags: |
          $(tag)
    - script: |
        sudo apt-get install wget apt-transport-https gnupg lsb-release -y
        wget -qO - https://aquasecurity.github.io/trivy-repo/pub.key | sudo apt-key add -
        echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt-get update
        sudo apt-get install trivy -y

        trivy image --exit-code 1 --severity CRITICAL $(repoName):$(tag)
      displayName: 'Scan image for vulnerabilities (Trivy)'
    - script: |
        # Login to ECR
        aws ecr get-login-password --region $(awsRegion) | docker login --username AWS --password-stdin $(AWS_ACCOUNT_ID).dkr.ecr.$(awsRegion).amazonaws.com

        # Tag and Push
        docker tag $(repoName):$(tag) $(AWS_ACCOUNT_ID).dkr.ecr.$(awsRegion).amazonaws.com/$(repoName):$(tag)
        docker push $(AWS_ACCOUNT_ID).dkr.ecr.$(awsRegion).amazonaws.com/$(repoName):$(tag)

        echo "Pushed image to ECR: $(AWS_ACCOUNT_ID).dkr.ecr.$(awsRegion).amazonaws.com/$(repoName):$(tag)"
      displayName: 'Push to ECR via AWS CLI'
      env:
        AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
        AWS_ACCOUNT_ID: $(AWS_ACCOUNT_ID)

# - stage: Deploy
#   displayName: Deploy to EC2
#   dependsOn: Build
#   condition: succeeded()
#   jobs:
#   - job: Deploy
#     displayName: Deploy to EC2
#     variables:
#       EC2_HOST: $(EC2_HOST)
#     steps:
#     - task: DownloadSecureFile@1
#       name: sshKey
#       displayName: 'Download SSH Key'
#       inputs:
#         secureFile: 'nodes-connect'
#     - script: |
#         # Fix line endings (CRLF -> LF) and ensure trailing newline
#         cat $(sshKey.secureFilePath) | tr -d '\r' > fixed_key
#         echo "" >> fixed_key
#         chmod 400 fixed_key
#         ssh -o StrictHostKeyChecking=no -i fixed_key ubuntu@$(EC2_HOST) \
#           'sudo apt-get update -y
#            sudo apt-get install -y docker.io
#            sudo systemctl start docker
#            sudo systemctl enable docker
#            sudo usermod -aG docker ubuntu
#            sudo apt install unzip -y
#            if ! aws --version; then
#              curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
#              unzip -o awscliv2.zip
#              sudo ./aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update
#            fi
#            aws --version'
#       displayName: 'Install Docker on EC2'
#       env:
#         AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
#         AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
#         AWS_ACCOUNT_ID: $(AWS_ACCOUNT_ID)
#         EC2_HOST: $(EC2_HOST)
#     - script: |
#         # Fix line endings (CRLF -> LF) and ensure trailing newline
#         cat $(sshKey.secureFilePath) | tr -d '\r' > fixed_key
#         echo "" >> fixed_key
#         chmod 400 fixed_key
#         ssh -o StrictHostKeyChecking=no -i fixed_key ubuntu@$(EC2_HOST) \
#           'aws ecr get-login-password --region $(awsRegion) | docker login --username AWS --password-stdin $(AWS_ACCOUNT_ID).dkr.ecr.$(awsRegion).amazonaws.com &&
#            docker pull $(AWS_ACCOUNT_ID).dkr.ecr.$(awsRegion).amazonaws.com/$(repoName):$(tag) &&
#            docker stop python-app || true &&
#            docker rm python-app || true &&
#            docker run -d -p 8080:5000 --name python-app \
#             -e NEWSDATA_API_KEY=$(NEWSDATA_API_KEY) \
#             -e AWS_REGION=eu-west-1 \
#             -e DYNAMODB_TABLE=neonews-demo \
#             -e S3_BUCKET_NAME=neonews-bucket-demo-123 \
#             $(AWS_ACCOUNT_ID).dkr.ecr.$(awsRegion).amazonaws.com/$(repoName):$(tag)
#           '
#       displayName: 'Deploy Docker Container on EC2'
#       env:
#         AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
#         AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
#         AWS_ACCOUNT_ID: $(AWS_ACCOUNT_ID)
#         NEWSDATA_API_KEY: $(NEWSDATA_API_KEY)
#         EC2_HOST: $(EC2_HOST)
