trigger: none

parameters:
- name: executeApply
  displayName: "Execute Terraform Apply"
  type: boolean
  default: false
- name: destroy
  displayName: "Execute Terraform Destroy"
  type: boolean
  default: false

resources:
- repo: self

variables:
- group: aws-ecr
- name: awsRegion
  value: 'eu-west-1'

stages:
- stage: Infrastructure
  displayName: Deploy Infrastructure
  jobs:
  - job: terraform
    displayName: Deploy Infrastructure with Terraform
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: DownloadSecureFile@1
      name: sshKey
      displayName: 'Download SSH Key'
      inputs:
        secureFile: 'nodes-connect.pub'
    - script: |
        sudo apt-get update && sudo apt-get install -y gnupg software-properties-common
        wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg > /dev/null
        echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
        sudo apt-get update && sudo apt-get install terraform

        cp $(sshKey.secureFilePath) "$(Build.Repository.LocalPath)/Final Boss/neonews/terraform/nodes-connect.pub"
      displayName: 'Install Terraform Manually'

    - script: terraform version
      displayName: 'Check Terraform Version'

    - script: |
        echo "----------------------Initializing Terraform...----------------------"
        terraform init
        echo "----------------------Terraform initialized.----------------------"
      displayName: 'Terraform Init'
      workingDirectory: '$(Build.SourcesDirectory)/Final Boss/neonews/terraform'
      env:
        AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
    - script: |
        echo "----------------------Terraform Plan...----------------------"
        terraform plan
      displayName: 'Terraform Plan'
      workingDirectory: '$(Build.SourcesDirectory)/Final Boss/neonews/terraform'
      env:
        AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
    - script: |
        echo "----------------------Terraform Apply...----------------------"
        terraform apply -auto-approve

        EC2_HOST=$(terraform output -raw ec2_public_ip)
        echo "##vso[task.setvariable variable=EC2_HOST;isOutput=true]$EC2_HOST"

        GROUP_ID=$(az pipelines variable-group list \
        --group-name "aws-ecr" \
        --query "[0].id" \
        --output tsv)

        echo "The ID for aws-ecr is: $GROUP_ID"
        echo "Updating EC2_HOST in variable group aws-ecr..."
        az pipelines variable-group variable update --group-id $(GROUP_ID) \
        --name EC2_HOST --value "$EC2_HOST" --detect true
      name: TerraformApply
      displayName: 'Terraform Apply'
      workingDirectory: '$(Build.SourcesDirectory)/Final Boss/neonews/terraform'
      env:
        AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
        AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)
      condition: and(succeeded(), eq('${{ parameters.executeApply }}', true), eq('${{ parameters.destroy }}', false))
    - script: |
        echo "----------------------Terraform Destroy...----------------------"
        terraform destroy -auto-approve
      displayName: 'Terraform Destroy'
      workingDirectory: '$(Build.SourcesDirectory)/Final Boss/neonews/terraform'
      env:
        AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
      condition: and(succeeded(), eq('${{ parameters.destroy }}', true), eq('${{ parameters.executeApply }}', false))
