frontend:
  replicaCount: 2
  image: stefandima1407/docker-learning:1.0.0
  containerPort: 80
  service:
    type: NodePort
    port: 80
    nodePort: 30080
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 250m
      memory: 128Mi

backend:
  replicaCount: 1
  image: redis:latest
  containerPort: 6379
  service:
    type: ClusterIP
    port: 6379
    name: redis-service
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 250m
      memory: 128Mi