apiVersion: v1
kind: Secret
metadata:
  name: {{ include "neonews-app.fullname" . }}-secret
  labels:
    {{- include "neonews-app.labels" . | nindent 4 }}
data:
  NEWSDATA_API_KEY: {{ .Values.secrets.newsdataApiKey | quote }}
  AWS_REGION: {{ .Values.secrets.awsRegion | quote }}
  S3_BUCKET_NAME: {{ .Values.secrets.s3BucketName | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.secrets.awsAccessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secrets.awsSecretAccessKey | quote }}
  DYNAMODB_TABLE: {{ .Values.secrets.dynamodbTable | quote }}
  AWS_ACCOUNT_ID: {{ .Values.secrets.awsAccountId | quote }}