services: 
  app: 
    build:
      context: ..
      dockerfile: Dockerfile
    image: neonews-webapp
    container_name: neonews
    ports:
      - "8080:5000"
    env_file:
      - ../src/.env
    restart: unless-stopped
    volumes:
      - ../src:/app
    networks:
      - app-network

networks:
  app-network:
    name: app-network
    driver: bridge